package-lock.json, package.json, src/components/usermainmanage/MainBanner.tsx, src/routes/usermainmanage/usermainrouter.tsx
=> docs : 경로 수정 및 MainBanner 퍼블리싱 작업

src/components/member/MemberModifyMD.tsx, src/pages/admin/member/MemberModify.tsx, src/pages/hooks/useCustomLogin.ts, src/redux/loginSlice.tsx
=> docs: MemberModifyPage 수정

src/layouts/Sidebar.tsx
=> docs:사이드바 수정

src/components/common/Modal.tsx, src/components/order/DetailOrMD.tsx, src/components/order/DetaileStyle.ts, src/components/order/TestMd.tsx, src/components/order/orderSlect/OrderPicker.tsx, src/components/table/OrderAllTable.tsx, src/pages/order/sub/OrderAllPage.tsx, src/styles/AdminBasic.ts
=> feat : 주문상세페이지 퍼블리싱 완료

src/components/community/Community.tsx, src/components/datas/data.tsx, src/layouts/AdminHeader.tsx, src/pages/ community/ CommunPage.tsx, src/routes/router.tsx
=> feat:게시판 추가

src/components/member/modal/MemberModifyMD.tsx, src/pages/admin/member/MemberModify.tsx
=> MemberModify 수정

package-lock.json, package.json, src/api/login/loginApi.js, src/components/member/modal/MemberModifyMD.tsx, src/components/member/modal/PostModal copy.tsx, src/components/select/MemberSelect.tsx, src/components/select/MonthlySelect.tsx, src/index.tsx, src/pages/admin/member/DailyReg.tsx, src/pages/admin/member/MemberModify.tsx, src/pages/admin/member/MonthlyReg.tsx, src/pages/hooks/useCustomLogin.js, src/redux/loginSlice.js
=> 월별 회원가입 구현

src/components/community/Community.tsx, src/layouts/AdminHeader.tsx
=> feat:스크룰 연습중

src/components/charts/OrderChartView.tsx, src/components/usermainmanage/MainBanner.tsx, src/components/usermainmanage/NewProduct.tsx, src/components/usermainmanage/PopProduct.tsx
=> docs : 사진 선택 기능 수정

src/components/community/Community.tsx, src/layouts/AdminBasic.tsx
=> feat:스크룰 추가

package.json, src/api/login/loginApi.js, src/api/member/memberApi.ts, src/components/select/MemberSelect.tsx, src/pages/admin/login/LoginPage.js, src/pages/admin/member/MemberModify.tsx, src/styles/member/memberstyle.ts, src/util/jwtUtil.js, tsconfig.json
=> docs: loginApi 일부수정

src/api/member/memberApi.ts, src/components/member/modal/MemberModifyMD.tsx, src/pages/admin/member/MemberDelete .tsx, src/pages/admin/member/MemberModify.tsx
=> 회원정보수정 데이터연동

src/api/order/orderAllApi.ts, src/pages/order/item/OrAllHeader.tsx
=> feat : order Api 연동중

src/api/chart/chartApi.ts, src/components/charts/DOrderChartView.tsx, src/components/charts/DSalesChartView.tsx, src/components/charts/MOrderChartView.tsx, src/components/charts/MSalesChartView.tsx, src/components/charts/OrderChart.tsx, src/components/charts/YOrderChartView.tsx
=> docs : chart API 연동 마무리

src/api/member/memberApi.ts, src/components/member/modal/MemberModifyMD.tsx, src/components/select/MemberSelect.tsx, src/pages/admin/member/DailyReg.tsx, src/pages/admin/member/MemberDelete .tsx, src/pages/admin/member/MemberModify.tsx, src/pages/admin/member/MonthlyReg.tsx
=> docs: monthly 차트 완성

src/api/chart/chartApi.ts, src/api/usermain/mainProductSetApi.ts, src/api/usermain/mainbannerApi.ts, src/components/charts/OrderChart.tsx, src/components/charts/SalesChart.tsx, src/components/usermainmanage/MainBanner.tsx, src/components/usermainmanage/MdRecommend.tsx, src/components/usermainmanage/NewProduct.tsx, src/components/usermainmanage/PopProduct.tsx, src/layouts/AdminBasic.tsx, src/pages/charts/ChartsIndex.tsx
고생하셨습니다 ...................................................................
=> docs : UserMainBanner 데이터 연동

package.json, src/components/member/DatePick.tsx, src/components/select/MemberSelect.tsx, src/pages/admin/member/MemberDelete .tsx, src/pages/admin/member/MemberModify.tsx
=> MemberModify 기능 구현

src/components/order/orderSlect/table/OrderAllTable.tsx, src/pages/order/item/OrAllHeader.tsx, src/pages/order/sub/OrderAllPage.tsx
=> feat : 주문 전체리스트 api 연동

src/components/usermainmanage/MainBanner.tsx
=> docs : mainbanner 수정

src/api/order/orderAllApi.ts, src/components/order/orderSlect/table/DpstTable.tsx, src/pages/TestPage.tsx, src/pages/order/item/OrAllHeader.tsx, src/pages/order/item/footer/OrAllFooter.tsx, src/pages/order/sub/OrderAllPage.tsx, src/routes/router.tsx
=> feat : 체크박스 수정

package.json, src/components/member/DatePick.tsx, src/index.tsx, src/pages/admin/member/MemberModify.tsx, tsconfig.json
=> RangePicker 수정

src/pages/order/item/OrAllHeader.tsx
=> feat : 체크박스 오류 수정완료

src/api/mail/mailApi.ts, src/api/member/memberApi.ts, src/api/order/orderAllApi.ts, src/components/member/DatePick.tsx, src/components/member/modal/MemberInfoSection.tsx, src/components/member/modal/MemberModifyMD.tsx, src/components/member/modal/MyBaby.tsx, src/components/member/modal/OrderInfoSection.tsx, src/components/member/modal/PostModal.tsx, src/pages/admin/member/MemberModify.tsx
=> modal 작업 완료

src/api/review/reviewApi.ts, src/components/review/HiddenReview.tsx, src/components/review/ReviewModal.tsx, src/components/review/ReviewSearch.tsx, src/components/usermainmanage/NewProduct.tsx, src/components/usermainmanage/PopProduct.tsx, src/components/usermainmanage/PutMd.tsx, src/components/usermainmanage/PutNew.tsx, src/layouts/AdminHeader.tsx, src/pages/review/ReviewIndex.tsx, src/pages/review/ReviewManage.tsx, src/pages/usermainmanage/UsermainIndex.tsx, src/routes/review/reviewrouter.tsx, src/routes/router.tsx, src/styles/review/reviewstyle.ts
안녕하세요 팀장님 날씨가 정말 좋네요 시간은 왜이렇게 빨리 갈까요
=> docs : 리뷰관리 페이지 데이터 연동중

src/api/review/reviewApi.ts, src/api/usermain/mainbannerApi.ts, src/components/review/HiddenReview.tsx, src/components/review/ReviewModal.tsx, src/components/review/ReviewSearch.tsx, src/components/usermainmanage/MainBanner.tsx, src/components/usermainmanage/MdRecommend.tsx, src/components/usermainmanage/NewProduct.tsx, src/components/usermainmanage/PutMd.tsx, src/components/usermainmanage/PutNew.tsx, src/components/usermainmanage/PutPop.tsx, src/styles/review/reviewstyle.ts, src/util/jwtUtil.ts
=> docs : 리뷰관리페이지 예외처리

src/api/usermain/mainProductSetApi.ts, src/components/review/HiddenReview.tsx, src/components/review/ReviewSearch.tsx, src/components/usermainmanage/MainBanner.tsx, src/components/usermainmanage/PutMd.tsx, src/components/usermainmanage/PutNew.tsx, src/components/usermainmanage/PutPop.tsx
=> docs : 검색기능 문제 수정 및 배너 업로드 및 수정 기능 구현

package.json, src/api/category/categoryApi.ts, src/components/category/CateData.tsx, src/components/category/CateSelec.tsx, src/layouts/AdminHeader.tsx, src/pages/category/CatePage.tsx, src/pages/category/Categorymain.tsx, src/pages/category/sub/Cate.ts, src/pages/category/sub/CateHeader.tsx, src/routes/category/CateRouter.tsx, src/routes/order/OrderRouter.tsx, src/routes/router.tsx
=> feat : 카테고리 api 삭제2개, 호출1

src/api/member/memberApi.ts, src/components/member/modal/MemberModifyMD.tsx, src/components/member/modal/OrderInfoSection.tsx, src/exel/member/DeleteExcel.tsx, src/exel/member/ModifyExcel.tsx, src/pages/admin/login/LoginPage.tsx, src/pages/admin/member/MemberDelete .tsx, src/pages/admin/member/MemberModify.tsx
=> docs: 알람 예외처리 구현

src/components/member/modal/OrderInfoSection.tsx, src/pages/admin/member/DailyReg.tsx, src/pages/admin/member/MemberDelete .tsx, src/pages/admin/member/MemberModify.tsx, src/pages/admin/member/MonthlyReg.tsx
=> Table undefined일때 예외처리

src/components/usermainmanage/MainBanner.tsx, src/components/usermainmanage/PutMd.tsx, src/components/usermainmanage/PutNew.tsx, src/components/usermainmanage/PutPop.tsx
=> docs : 배너 수정기능 오류 수정
